//
//  CircleDiagram3.swift
//
//  Created on Sep 30, 2018.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import UIKit



class CircleDiagram3: NSObject {
    
    
    //MARK: - Canvas Drawings
    
    /// Page 1
    
    class func drawUntitled(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 200, height: 204), resizing: ResizingBehavior = .aspectFit) {
        /// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        /// Resize to Target Frame
        context.saveGState()
        let resizedFrame = resizing.apply(rect: CGRect(x: 0, y: 0, width: 200, height: 204), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 200, y: resizedFrame.height / 204)
        context.translateBy(x: -424, y: -75)
        
        /// Group
        do {
            context.saveGState()
            context.translateBy(x: 424, y: 75)
            
            /// Circle 3
            let circle3 = NSMutableAttributedString(string: "Circle 3")
            circle3.addAttribute(.font, value: UIFont(name: "Helvetica", size: 18)!, range: NSRange(location: 0, length: circle3.length))
            do {
                let paragraphStyle = NSMutableParagraphStyle()
                paragraphStyle.alignment = .center
                circle3.addAttribute(.paragraphStyle, value: paragraphStyle, range: NSRange(location: 0, length: circle3.length))
            }
            context.saveGState()
            circle3.draw(at: CGPoint(x: 69, y: 89))
            context.restoreGState()
            
            context.restoreGState()
        }
        
        /// Oval
        let oval = UIBezierPath()
        oval.move(to: CGPoint(x: 84, y: 170))
        oval.addCurve(to: CGPoint(x: 168, y: 85), controlPoint1: CGPoint(x: 130.39, y: 170), controlPoint2: CGPoint(x: 168, y: 131.94))
        oval.addCurve(to: CGPoint(x: 123.51, y: 9.97), controlPoint1: CGPoint(x: 168, y: 52.51), controlPoint2: CGPoint(x: 149.98, y: 24.27))
        oval.addCurve(to: CGPoint(x: 84, y: 0), controlPoint1: CGPoint(x: 111.73, y: 3.61), controlPoint2: CGPoint(x: 98.28, y: 0))
        oval.addCurve(to: CGPoint(x: 66.34, y: 1.88), controlPoint1: CGPoint(x: 77.94, y: 0), controlPoint2: CGPoint(x: 72.03, y: 0.65))
        oval.addCurve(to: CGPoint(x: 0, y: 85), controlPoint1: CGPoint(x: 28.43, y: 10.09), controlPoint2: CGPoint(x: 0, y: 44.19))
        oval.addCurve(to: CGPoint(x: 84, y: 170), controlPoint1: CGPoint(x: 0, y: 131.94), controlPoint2: CGPoint(x: 37.61, y: 170))
        oval.close()
        oval.move(to: CGPoint(x: 84, y: 170))
        context.saveGState()
        context.translateBy(x: 440, y: 93)
        oval.lineWidth = 1
        UIColor(hue: 0.374, saturation: 0.646, brightness: 0.888, alpha: 1).setStroke()
        oval.stroke()
        context.restoreGState()
        
        /// Oval 2
        let oval2 = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 30, height: 32))
        context.saveGState()
        context.setAlpha(0.49)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 503, y: 77)
            UIColor(hue: 0.463, saturation: 0.646, brightness: 0.888, alpha: 1).setFill()
            oval2.fill()
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        /// Oval 2
        let oval3 = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 30, height: 32))
        context.saveGState()
        context.setAlpha(0.49)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 438, y: 203)
            UIColor(hue: 0.463, saturation: 0.646, brightness: 0.888, alpha: 1).setFill()
            oval3.fill()
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        /// Oval 2
        let oval4 = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 30, height: 32))
        context.saveGState()
        context.setAlpha(0.49)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 468, y: 235)
            UIColor(hue: 0.463, saturation: 0.646, brightness: 0.888, alpha: 1).setFill()
            oval4.fill()
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        /// Oval 2
        let oval5 = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 30, height: 32))
        context.saveGState()
        context.setAlpha(0.49)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 453, y: 93)
            UIColor(hue: 0.463, saturation: 0.646, brightness: 0.888, alpha: 1).setFill()
            oval5.fill()
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        /// Oval 2
        let oval6 = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 30, height: 32))
        context.saveGState()
        context.setAlpha(0.49)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 578, y: 125)
            UIColor(hue: 0.463, saturation: 0.646, brightness: 0.888, alpha: 1).setFill()
            oval6.fill()
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        /// Oval 2
        let oval7 = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 30, height: 32))
        context.saveGState()
        context.setAlpha(0.49)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 593, y: 171)
            UIColor(hue: 0.463, saturation: 0.646, brightness: 0.888, alpha: 1).setFill()
            oval7.fill()
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        /// Oval 2
        let oval8 = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 30, height: 32))
        context.saveGState()
        context.setAlpha(0.49)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 518, y: 247)
            UIColor(hue: 0.463, saturation: 0.646, brightness: 0.888, alpha: 1).setFill()
            oval8.fill()
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        /// Oval 2
        let oval9 = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 30, height: 32))
        context.saveGState()
        context.setAlpha(0.49)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 563, y: 219)
            UIColor(hue: 0.463, saturation: 0.646, brightness: 0.888, alpha: 1).setFill()
            oval9.fill()
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        /// Oval 2
        let oval10 = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 30, height: 32))
        context.saveGState()
        context.setAlpha(0.49)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 548, y: 93)
            UIColor(hue: 0.463, saturation: 0.646, brightness: 0.888, alpha: 1).setFill()
            oval10.fill()
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        /// Oval 2
        let oval11 = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 30, height: 32))
        context.saveGState()
        context.setAlpha(0.49)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 425, y: 146)
            UIColor(hue: 0.463, saturation: 0.646, brightness: 0.888, alpha: 1).setFill()
            oval11.fill()
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        context.restoreGState()
    }
    
    /// Symbols
    
    class func drawUser(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 168, height: 161), resizing: ResizingBehavior = .aspectFit) {
        /// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        /// Resize to Target Frame
        context.saveGState()
        let resizedFrame = resizing.apply(rect: CGRect(x: 0, y: 0, width: 168, height: 161), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 168, y: resizedFrame.height / 161)
        
        /// Oval
        let oval = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 168, height: 161))
        context.saveGState()
        UIColor(white: 0.847, alpha: 1).setFill()
        oval.fill()
        oval.lineWidth = 1
        UIColor(white: 0.592, alpha: 1).setStroke()
        oval.stroke()
        context.restoreGState()
        
        context.restoreGState()
    }
    
    
    //MARK: - Canvas Images
    
    /// Page 1
    
    class func imageOfUntitled() -> UIImage {
        struct LocalCache {
            static var image: UIImage!
        }
        if LocalCache.image != nil {
            return LocalCache.image
        }
        var image: UIImage
        
        UIGraphicsBeginImageContextWithOptions(CGSize(width: 200, height: 204), false, 0)
        CircleDiagram3.drawUntitled()
        image = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        
        LocalCache.image = image
        return image
    }
    
    /// Symbols
    
    class func imageOfUser() -> UIImage {
        struct LocalCache {
            static var image: UIImage!
        }
        if LocalCache.image != nil {
            return LocalCache.image
        }
        var image: UIImage
        
        UIGraphicsBeginImageContextWithOptions(CGSize(width: 168, height: 161), false, 0)
        CircleDiagram3.drawUser()
        image = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        
        LocalCache.image = image
        return image
    }
    
    
    //MARK: - Resizing Behavior
    
    enum ResizingBehavior {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.
        
        func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }
            
            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)
            
            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }
            
            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
    
    
}
